Discipline.create(:id => 1, :name => "Português")
Discipline.create(:id => 2, :name => "Matematica")
Discipline.create(:id => 3, :name => "Ciencias")
Discipline.create(:id => 4, :name => "História")
Discipline.create(:id => 5, :name => "Quimica")
Discipline.create(:id => 6, :name => "Fisica")
Discipline.create(:id => 7, :name => "Educação Fisica")
