# mysql
#development:
#  adapter: mysql2
#  encoding: utf8
#  reconnect: false
#  database: school
#  pool: 5
#  username: root
#  password: root
#  host: localhost
  #socket: /var/run/mysqld/mysqld.sock
  
  #POSTGRESQL
development:
  adapter: postgresql
  encoding: unicode
  database: school
  pool: 5
  host: localhost
  username: postgres
  password: 123456
  
#production:
#  adapter: postgresql
#  encoding: unicode
#  database: school_production
#  pool: 5
#  host: localhost
#  username: postgres
#  password: 123456
    